// Generated by gencpp from file topic_node/PerResponse.msg
// DO NOT EDIT!


#ifndef TOPIC_NODE_MESSAGE_PERRESPONSE_H
#define TOPIC_NODE_MESSAGE_PERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topic_node
{
template <class ContainerAllocator>
struct PerResponse_
{
  typedef PerResponse_<ContainerAllocator> Type;

  PerResponse_()
    : sum(0)  {
    }
  PerResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::topic_node::PerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic_node::PerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PerResponse_

typedef ::topic_node::PerResponse_<std::allocator<void> > PerResponse;

typedef boost::shared_ptr< ::topic_node::PerResponse > PerResponsePtr;
typedef boost::shared_ptr< ::topic_node::PerResponse const> PerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic_node::PerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic_node::PerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic_node::PerResponse_<ContainerAllocator1> & lhs, const ::topic_node::PerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic_node::PerResponse_<ContainerAllocator1> & lhs, const ::topic_node::PerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topic_node::PerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_node::PerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_node::PerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_node::PerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_node::PerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_node::PerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic_node::PerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::topic_node::PerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::topic_node::PerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic_node/PerResponse";
  }

  static const char* value(const ::topic_node::PerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic_node::PerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 服务器响应发送的数据\n"
"int32 sum\n"
"\n"
;
  }

  static const char* value(const ::topic_node::PerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic_node::PerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic_node::PerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic_node::PerResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_NODE_MESSAGE_PERRESPONSE_H
